package Controller

import (
	"Inventory_Management/Models"
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// AddProduct - Add a new product to the database
func AddProduct(c *gin.Context) {
	username,pass,ok := c.Request.BasicAuth()
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error":"please provide login credentials"})
		return
	}
	err := Models.AuthRetailer(username, pass)
	if err != nil{
		c.JSON(http.StatusBadRequest, gin.H{"error":err.Error()})
		return
	}
	var product Models.Product
	if err := c.ShouldBindJSON(&product); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Please add valid product details"})
		return
	} else {
		if err := Models.AddProduct(&product); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		} else {
			c.JSON(http.StatusOK, product)
		}
	}
}

//GetProducts - Get all products available in the database
func GetProducts(c *gin.Context) {
	var products []Models.Product
	err := Models.GetProducts(&products)
	if err != nil {
		c.AbortWithStatus(http.StatusNotFound)
	} else {
		c.JSON(http.StatusOK, products)
	}
}

//UpdateProduct - Update existing product details
func UpdateProduct(c *gin.Context) {

	username,pass,ok := c.Request.BasicAuth()
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error":"please provide login credentials"})
		return
	}
	err := Models.AuthRetailer(username, pass)
	if err != nil{
		c.JSON(http.StatusBadRequest, gin.H{"error":err.Error()})
		return
	}

	var product Models.Product
	uid := c.Params.ByName("uid")
	err = Models.AuthProductRetailer(&product, uid, username)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	c.BindJSON(&product)
	err = Models.UpdateProduct(&product, uid)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err})
	} else {
		c.JSON(http.StatusOK, product)
	}
}

//PlaceOrder - Place order function takes product ID, quantity, username to place a new order
func PlaceOrder(c *gin.Context) {
	var order Models.Order

	username,pass,ok := c.Request.BasicAuth()
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error":"please provide login credentials"})
		return
	}
	err := Models.AuthUser(username, pass)
	if err != nil{
		c.JSON(http.StatusBadRequest, gin.H{"error":err.Error()})
		return
	}

	c.BindJSON(&order)
	//c.Request.Header
	//c.Request.Context()
	//c.GetHeader("username")

	err = Models.PlaceOrder(&order,username)
	if err != nil {
		//fmt.Println(err)
		c.JSON(http.StatusBadRequest, gin.H{"Error": err.Error()})
	} else {
		c.JSON(http.StatusOK, order)
	}
}

// GetUserOrders - Get all orders of the user (username need to be taken from the logged in user; will do that after implementing the authentication part)
func GetUserOrders(c *gin.Context) {
	var orders []Models.Order
	username,pass,ok := c.Request.BasicAuth()
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error":"please provide login credentials"})
		return
	}
	err := Models.AuthUser(username, pass)
	if err != nil{
		c.JSON(http.StatusBadRequest, gin.H{"error":err.Error()})
		return
	}
	//username := c.Params.ByName("username")
	err = Models.GetUserOrders(&orders, username)
	if err != nil {
		//fmt.Println(err)
		c.JSON(http.StatusBadRequest, gin.H{"message": "User not found"})
	} else {
		c.JSON(http.StatusOK, orders)
	}
}

// GetRetailerOrders - Get all orders placed
func GetRetailerOrders(c *gin.Context) {
	var orders []Models.Order

	username,pass,ok := c.Request.BasicAuth()
	if !ok {
		c.JSON(http.StatusUnauthorized, gin.H{"error":"please provide login credentials"})
		return
	}
	err := Models.AuthRetailer(username, pass)
	if err != nil{
		c.JSON(http.StatusBadRequest, gin.H{"error":err.Error()})
		return
	}

	retailerid := c.Params.ByName("retailerid")
	err = Models.GetRetailerOrders(&orders, retailerid)
	if err != nil {
		fmt.Println(err)
		c.AbortWithStatus(http.StatusNotFound)
	} else {
		c.JSON(http.StatusOK, orders)
	}
}

//CreateUser - Creating user takes username, name, email data (all are required)
func CreateUser(c *gin.Context) {
	var user Models.User

	err := c.ShouldBindJSON(&user)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "Please provide valid details"})
		return
	}

	if err := Models.CreateUser(&user); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"message": "Try again with different username"})
	} else {
		c.JSON(http.StatusOK, user)
	}

}

//GetUser- Get all users from the database (should be accessed by admin only; need to implement role based authentication)
func GetAllUsers(c *gin.Context) {
	var users []Models.User
	err := Models.GetAllUsers(&users)
	if err != nil {
		c.AbortWithStatus(http.StatusNotFound)
	} else {
		c.JSON(http.StatusOK, users)
	}
}

func CreateRetailer(c *gin.Context) {
	var retailer Models.Retailer
	err := c.ShouldBindJSON(&retailer) // retailer ID should be generated by the server and given to the retailer (that functionality is not added yet)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Please provide valid details"})
		return
	}

	if err := Models.CreateRetailer(&retailer); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Try again with different username"})
	} else {
		c.JSON(http.StatusOK, retailer)
	}
}
